# Common parameters 
seed = 42
num_steps = 800000
batch_size = 512
gamma = 0.99
lr = 1e-4
save_interval = 10000
save_dir = "ckpt"
log_interval = 1000

# Environment parameters
frame_skip = 1
frame_stack = 4

# PPO-specific parameters
horizon = 1024
epochs_per_step = 10
gae_lambda = 0.95
clip = 0.2
value_coef = 0.5
entropy_coef = 0.005