[sac]
batch_size = 256
gamma = 0.95
actor_lr = 3e-5  # Reduced from 3e-4
critic_lr = 3e-5  # Reduced from 3e-4
alpha_lr = 3e-5  # Reduced to match actor/critic
buffer_size = 500000
tau = 0.005
updates_per_step = 1
start_steps = 10000
target_update_interval = 2
reward_scale = 0.1
max_grad_norm = 0.1
max_episodes = 850
gradient_steps = 1

[evaluation]
eval_freq = 25000
eval_episodes = 10

[lr_scheduler]
patience = 15
factor = 0.5
min_lr = 1e-6

[exploration]
noise_scale_start = 0.2
noise_decay = 0.9997
min_noise = 0.02